export const SEARCH_GAME = 'SEARCH_GAME';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const GAME_DETAIL_LOOKUP = 'GAME_DETAIL_LOOKUP';
export const ADD_GAME_TO_COLLECTION = 'ADD_GAME_TO_COLLECTION';
export const ADD_GAME_SUCCESSFUL = 'ADD_GAME_SUCCESSFUL';
